authentication,validation,errorhandling Modules
wecode-bootcamp-korea/48-2nd-TeamElbow-backend pull request #5
Opened 2023-08-23 15:42 UTC by MinsungChun

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 모듈 유효성검사 /회원가입시 기재사항 유효성검사 / 토큰기능 추가 / 글로벌 에러핸들러 추가
- 
<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
/signup 에서 email, userid, birthday  내용 date 이면 1991-01-01 예시와 같이 입력 되지 않으면 에러메세지 전송

- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
3. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
<img width="1024" alt="image" src="https://github.com/wecode-bootcamp-korea/48-2nd-TeamElbow-backend/assets/140421347/00c82403-1d24-45f4-b028-9a230fc0a5b3">

5. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지

<img width="546" alt="image" src="https://github.com/wecode-bootcamp-korea/48-2nd-TeamElbow-backend/assets/140421347/b36db190-ced8-4c27-ad3d-648ff8156c0a">

7. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항

2023-08-24 07:04 UTC, kyeongraekim requested changes

2023-08-24 07:04 UTC, kyeongraekim commented on api/routes/index.js
> +module.exports = {router};
- main으로의 머지를 희망하는 코드내에는 불필요한 주석이 함께 있어서는 안됩니다.
- 해당 내용을 살릴지, 아니면 다른 브랜치 기능 개발 시 포함시킬지 판단하여 삭제 또는 유지등의 판단을 진행해주세요!

2023-08-25 05:50 UTC, MinsungChun commented
불필요한 주석 삭제 완료하였습니다.

2023-08-25 06:02 UTC, kyeongraekim approved these changes

2023-08-25 06:02 UTC, merged