[정동민] movie list 기능
wecode-bootcamp-korea/48-2nd-TeamElbow-backend pull request #6
Opened 2023-08-27 08:25 UTC by seeperk

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
-클라이언트에서 약속된 endpoint로 요청이 들어올 시 무비리스트, 영화 상세정보 데이터를 전달하는 기능 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 예매율 순으로 정렬하기 위해 예매율 계산 기능 구현
- 예매율, 가나다 순으로 전달하기 위해 쿼리빌더 사용

<br />

## :: 테스트 결과 이미지

무비 차트
![image](https://github.com/wecode-bootcamp-korea/48-2nd-TeamElbow-backend/assets/135579112/8fcb1690-68ba-42e7-a778-bb35afc34aec)

영화 상세정보
![image](https://github.com/wecode-bootcamp-korea/48-2nd-TeamElbow-backend/assets/135579112/6a9bfbef-77c8-438b-b22c-e1214a74027a)

<br />

## :: 기타 질문 및 특이 사항
- 현재는 모든 영화가 상영중이라는 전제이지만 상영예정작 및 상영종료 영화가 있다면 movies table에 상영상태를 나타내는 column 을 추가해야 할까요??
- 현재는 모수가 적어 요청이 들어올 때마다 예매율을 계산하지만 모수가 많이지면 무리가 생길 수 있다고 생각합니다. 이런 경우 지정된 시간마다 예매율이 계산되도록하는 기능을 사용해도 좋을까요??

2023-08-27 08:43 UTC, kyeongraekim requested changes
현재 movie List 의 내용에 불필요한 member의 내용도 함께 작업이 되어 기입되어 있습니다. 전체적으로 브랜치 분리를 올바르게 수행하여주세요!

2023-08-27 08:49 UTC, kyeongraekim requested changes

2023-08-27 08:49 UTC, kyeongraekim commented on api/controllers/movieController.js
> +  await movieService.recordBookingRate(req);
- bookingRate를 기록(저장)하는 내용을 테이블 내 별도의 형태로 저장하는 내용이, 굳이 Layered Pattern 내에 하나의 흐름으로 적용되어서 코드로서 기능할 필요는 없어 보입니다.
- 즉, 영화 예매를 하는 API의 reserveMovie(가칭) 모듈에서 최종적으로, 예약이 완료된 시점에서의 Insert 구문이 적용되어 이를 업데이트 해주는 방향으로 설정하는 것이 더 효율적으로 보여집니다.
- 즉 영화 정보를 조회하는 요청건 마다 영화의 예매율을 업데이트 하는 것이 아닌, 예매가 이루어지는 시점에서 예매율을 업데이트 하는 것 입니다.
- 하지만 이 방법도 굳이 효율적인 방법은 아닌 것으로 보여집니다. 왜냐하면, 트래픽 요청이 들어올 때마다 해당 db를 히트하며 예매율을 수정하는 방법이기 때문입니다. 예매율에 대한 계산은 하루에 한 번, 혹은 특정 시간마다 한 번씩 이루어져도 괜찮다는 생각입니다.

2023-08-29 07:08 UTC, seeperk commented
> 현재 movie List 의 내용에 불필요한 member의 내용도 함께 작업이 되어 기입되어 있습니다. 전체적으로 브랜치 분리를 올바르게 수행하여주세요!

![image](https://github.com/wecode-bootcamp-korea/48-2nd-TeamElbow-backend/assets/135579112/c687f965-90c5-4b95-a486-8713c8d0a21c)
멤버 쪽을 원상태로 복구하여 바뀐 부분이 없는데 깃에서는 수정된 사항이 있는거로 인식하네요 원인이 뭘까요??
예매율 계산부분은 말씀해주신대로 이 브랜치에서 제거 하였습니다.

2023-08-29 07:59 UTC, kyeongraekim approved these changes
LGTM!~ 동민님 이제 다른 팀원분들의 코드는 물론 및 전체적인 플로우 함께 살펴봐주시면서 놓친 부분은 없나 큰 그림을 함께 잡아나가주세요!

2023-08-29 07:59 UTC, merged

2023-08-31 05:26 UTC, seeperk commented
현재 가격을 결정하는 요소가 너무 많아 단순화를 거쳐 가격정보를 프론트 코드에 미리 넣어두기로 하였고 조조상영 여부만 백에서 프론트로 전달하기로 하여 컨트롤러와 라우터도 약간의 수정이 있었습니다.