[TeamElbow] feature/selectSeats
wecode-bootcamp-korea/48-2nd-TeamElbow-backend pull request #7
Opened 2023-08-30 06:20 UTC by seeperk

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 좌석의 예매 가능 여부 표현
- 좌석의 예매 가격 표현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 좌석의 예매 가능 여부 표시
- 좌석의 예매 가격 표시
- 좌석선택 창에 영화 기본정보 표시

<br />

## :: 테스트 결과 이미지
![image](https://github.com/wecode-bootcamp-korea/48-2nd-TeamElbow-backend/assets/135579112/9fb0601a-bacc-48e6-85d0-06347208fde9)
![image](https://github.com/wecode-bootcamp-korea/48-2nd-TeamElbow-backend/assets/135579112/1aaeeae5-7d75-410a-a4f9-ac32f5d3d28b)
![image](https://github.com/wecode-bootcamp-korea/48-2nd-TeamElbow-backend/assets/135579112/79b5c475-4f68-4d0a-9f5c-bd2e5eb47ff6)

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-08-30 08:42 UTC, kyeongraekim requested changes

2023-08-30 08:42 UTC, kyeongraekim commented on api/services/bookingService.js
> +};
```javascript
const DaysOfWeek = {
  Mon: "월",
  Tue: "화",
  Wed: "수",
  Thu: "목",
  Fri: "금",
  Sat: "토",
  Sun: "일"
};

const getDayTranslation = (day) => {
  const shortenedDay = day.substring(0, 3);
  return DaysOfWeek[shortenedDay] || day;
};

const getMovieInformationInSeatsSelection = async (screeningId) => {
  const [movieInformationInSeatsSelection] = await bookingDao.getMovieInformationInSeatsSelection(screeningId);
  const { screeningDate } = movieInformationInSeatsSelection;

  movieInformationInSeatsSelection.screeningDate = await getDayTranslation(screeningDate);

  return movieInformationInSeatsSelection;
};

2023-08-30 08:42 UTC, kyeongraekim commented on api/services/bookingService.js
> +};
- 현재 작성해주신 방법은, if-else의 불필요한 분기가 많이 보여집니다.
- 위 내용처럼 if의 분기를 최소화한, 구조화 작업을 통해서 코드의 로직이 linear 흘러갈 수 있게 수정에 도전해보세요!

2023-08-31 05:27 UTC, seeperk commented
현재 가격을 결정하는 요소가 너무 많아 단순화를 거쳐 가격정보를 프론트 코드에 미리 넣어두기로 하였고 조조상영 여부만 백에서 프론트로 전달하기로 하여 컨트롤러와 라우터도 약간의 수정이 있었습니다.

2023-08-31 05:53 UTC, kyeongraekim requested changes
LGTM

2023-08-31 05:53 UTC, kyeongraekim commented on api/services/bookingService.js
> +};
- 해당 내용의 코드 모습이, 단편적인 코드 테스트용 코드처럼 흘러가고 있네요!
- 상용화될 웹 개발 코드에서는 i, j 와 같은 축약 변수의 사용을 최대한 지양해주셔야 합니다.
- 또한 if-else 구조의 모양을 아래와 같이 좀 더 깔끔하게 쳐낼 수 있어 보이는데 한 번 아래 모습을 참고하여 올바른 기능으로 수정해보세요!

```javascript
const getTotalPrice = async (screeningId, seatId, audienceType) => {
  const seatIds = Array.isArray(seatId) ? seatId : [seatId];
  const audienceTypes = Array.isArray(audienceType) ? audienceType : [audienceType];

  const prices = await Promise.all(seatIds.map((id, index) => getSeatPrice(screeningId, id, audienceTypes[index])));

  return prices.reduce((total, price) => total + price, 0);
};

2023-08-31 05:53 UTC, kyeongraekim commented on api/services/bookingService.js
> +};
- 위 내용 중 Promise.all()은 내부 메소드 함수의 최종 내용의 계산이 완료된 시점에 해당 비동기가 시행되어, 더 효과적인 연산을 가능케 하며, 
- 아래 reduce() 구문은, 배열안에 내부 숫자를 모두 더하는데 용이한 자바스크립트 내 메소드입니다! 해당 내용 MDN 페이지에서 참고하여 적용을 도전해보세요!

2023-09-01 04:44 UTC, merged